apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  labels:
    {{- include "node-operation-validator.labels" . | nindent 4 }}
data:
  forbiddenUsers: {{ join "," .Values.config.forbiddenUsers }}