apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "node-operation-validator.fullname" . }}-proxy-rolebinding
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: node-operation-validator
    app.kubernetes.io/part-of: node-operation-validator
  {{- include "node-operation-validator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "node-operation-validator.fullname" . }}-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ include "node-operation-validator.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}