apiVersion: v1
kind: ConfigMap
metadata:
  name: reasons-config
  labels:
    {{- include "node-operation-validator.labels" . | nindent 4 }}
data:
  reasons: |
    {{- range .Values.reasons.allowedReasons }}
    {{ . }}
    {{- end }}