apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "node-operation-validator.fullname" . }}-selfsigned-issuer
  labels:
  {{- include "node-operation-validator.labels" . | nindent 4 }}
spec:
  selfSigned: {}