apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "node-operation-validator.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "node-operation-validator.fullname" . }}-serving-cert
  labels:
  {{- include "node-operation-validator.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "node-operation-validator.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-v1-node
  failurePolicy: Ignore
  name: nodeoperation.dana.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - DELETE
    - CREATE
    - UPDATE
    resources:
    - nodes
  sideEffects: None